from src.domain.ledger import models as ledger_models  # noqa: F401
from src.domain.security import models as security_models  # noqa: F401
from src.domain.payments import models as payments_models  # noqa: F401
from src.domain.pix import models as pix_models  # noqa: F401
from src.domain.cards import models as cards_models  # noqa: F401
from src.domain.loans import models as loans_models  # noqa: F401
from src.domain.investments import models as investments_models  # noqa: F401
from src.domain.insurance import models as insurance_models  # noqa: F401
from src.domain.billing import models as billing_models  # noqa: F401
from src.domain.pj import models as pj_models  # noqa: F401
from src.domain.open_banking import models as open_banking_models  # noqa: F401
from src.domain.support import models as support_models  # noqa: F401
from src.domain.settings import models as settings_models  # noqa: F401
from src.domain.utilities import models as utilities_models  # noqa: F401
from src.domain.compliance import models as compliance_models  # noqa: F401
from src.domain.reconciliation import models as reconciliation_models  # noqa: F401
from src.domain.fraud import models as fraud_models  # noqa: F401
from src.domain.notifications import models as notifications_models  # noqa: F401
from src.domain.regulatory import models as regulatory_models  # noqa: F401
from src.domain.ml import models as ml_models  # noqa: F401
from src.domain.feature_flags import models as feature_flag_models  # noqa: F401
